### ISSUE TITLE
Encoding issue in item names

### ISSUE THREAD

**Issue by Nalha** [guiguilechat/JCELechat#28] opened 2019-12-15 13:40 UTC
There are some items with � in their names

  �� Chemosh: entity/NPCDreadnought
  ��� Apocalypse: entity/NPCBattleship
  ��� Kestrel: entity/NPCFrigate
  YC118 Succession Trial Champion���s Decree – House Khanid:
   name: ‘Jormungandr��� Explosive Reaper Blueprint

You can find one on row 100 in this:
https://github.com/guiguilechat/JCELechat/blob/815924449d092a9b1bf981cbfe0372073bd5ae48/model/sde/SDE-Items/src/generated/resources/SDE/items/blueprint/SuperWeaponBlueprint.yaml

**Comment by guiguilechat** [comment] 2019-12-15 14:34
yes. I have no idea where this comes from. Sometimes I relaunch the item compiler and I have another set of names with bad encoding. I tried several things but could not fix this. This is very low priority for me so I don't really care.

**Comment by Nalha** [comment] 2019-12-15 14:44
Ah ok, might look into it some day

**Comment by guiguilechat** [comment] 2019-12-15 15:25
It comes from the SDE. Whatever encoding I select, I have some names that are badly encoded. 

`sed -n "905000,905100p" typeIDs.yaml > typescut.txt
[typescut.txt](https://github.com/guiguilechat/JCELechat/files/3965064/typescut.txt)
`

**Comment by guiguilechat** [comment] 2019-12-15 15:29
basically that's one of the reasons why I should use ESI

https://github.com/guiguilechat/JCELechat/issues/18

https://esi.evetech.net/v3/universe/types/41451

**Comment by guiguilechat** [comment] 2020-02-26 14:36
CCP Prism confirmed it's on their end.

**Comment by guiguilechat** [comment] 2020-04-27 12:41
should be fixed by compiling from ESI instead of SDE.

**Closed** 2020-04-28 22:14 UTC
Labels: SDE, wontfix
